// Generated by CoffeeScript 1.4.0
(function() {

  $(function() {
    new FastClick(document.body);
    return Nimbus.Auth.set_app_ready(function() {
      console.log("app ready called");
      if (Nimbus.Auth.authorized()) {
        return $("#loginModal").removeClass("active");
      }
    });
  });

  window.toggle_slide = function() {
    return $("body").toggleClass("slide_left");
  };

  window.log_out = function() {
    Nimbus.Auth.logout();
    $("body").toggleClass("slide_left");
    return $("#loginModal").addClass("active");
  };

}).call(this);
