// Generated by CoffeeScript 1.4.0
(function() {

  $(function() {
    var context, keyboard, nodes, settings;
    new FastClick(document.body);
    Nimbus.Auth.set_app_ready(function() {
      console.log("app ready called");
      if (Nimbus.Auth.authorized()) {
        return $("#loginModal").removeClass("active");
      }
    });
    window.construct_instruction(window.current_song);
    settings = {
      id: "keyboard",
      width: 900,
      height: 200,
      startNote: "C3",
      whiteNotesColour: "white",
      blackNotesColour: "black",
      hoverColour: "yellow",
      keyboardLayout: "en"
    };
    keyboard = qwertyHancock(settings);
    context = new webkitAudioContext();
    nodes = [];
    keyboard.keyDown(function(note, frequency) {
      var gainNode, oscillator;
      console.log("note", note, "frequency", frequency);
      oscillator = context.createOscillator();
      gainNode = context.createGainNode();
      oscillator.type = 1;
      oscillator.frequency.value = frequency;
      gainNode.gain.value = 0.3;
      oscillator.connect(gainNode);
      if (typeof oscillator.noteOn !== "undefined") {
        oscillator.noteOn(0);
      }
      gainNode.connect(context.destination);
      return nodes.push(oscillator);
    });
    return keyboard.keyUp(function(note, frequency) {
      var i, name, _results;
      console.log("note", note, "frequency", frequency);
      if (note === window.current_song[window.current]) {
        window.current = window.current + 1;
        console.log("match", window.current);
        name = "#n" + (window.current - 1);
        $(name).addClass("done");
      }
      i = 0;
      _results = [];
      while (i < nodes.length) {
        if (Math.round(nodes[i].frequency.value) === Math.round(frequency)) {
          if (typeof nodes[i].noteOff !== "undefined") {
            nodes[i].noteOff(0);
          }
          nodes[i].disconnect();
        }
        _results.push(i++);
      }
      return _results;
    });
  });

  window.toggle_slide = function() {
    return $("body").toggleClass("slide_left");
  };

  window.log_out = function() {
    Nimbus.Auth.logout();
    $("body").toggleClass("slide_left");
    return $("#loginModal").addClass("active");
  };

  window.current_song = ["C3", "D3", "E3", "F3", "G3"];

  window.construct_instruction = function(song) {
    var a, counter, k, key, match, s, x, _i, _len, _results;
    window.current = 0;
    match = {
      'C3': 'Do',
      'D3': 'Re',
      'E3': 'Me',
      'F3': 'Fa',
      'G3': 'So',
      'A3': "La",
      'B3': "Se",
      "C3": "Do"
    };
    key = {
      'C3': 'A',
      'D3': 'S',
      'E3': 'D',
      'F3': 'F',
      'G3': 'G',
      'A3': "A",
      'B3': "B",
      "C3": "C"
    };
    counter = 0;
    _results = [];
    for (_i = 0, _len = song.length; _i < _len; _i++) {
      a = song[_i];
      x = match[a];
      k = key[a];
      s = "\"<div class=\"note\" id=\"n" + counter + "\"><span class=\"what\">" + x + "</span> <br /><span class=\"key\">" + k + "</span></div>";
      console.log(s);
      $("#instruction").append(s);
      _results.push(counter = counter + 1);
    }
    return _results;
  };

}).call(this);
